// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './bag.css';


export default class Bag extends React.Component {
  render() {
    return (
      <div className="bag-bag-2">
          <div className="bag-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1a68/882f/28e8dcb780f21fc9bf64142172e72723" className="bag-image-7" /> 
          </div>
          <div className="bag-1">
              <div className="bag-pull_button-9" /> 
          </div>
      </div>
    );
  }
};
