// Generated by https://pagedraw.io/pages/15246
// import React from 'react';
import './baggrund.css';
import  React, { Component } from 'react';

class Baggrund extends Component {
  constructor(props) {
    super(props);
    this.state = {  };
    this.GeoOptions = { enableHighAccuracy: true, timeout: 20000, maximumAge: 0, distanceFilter: 1} // Hardcoded for now

    this.GetPosition = this.GetPosition.bind(this);
    
  }

GetPosition()
{

    navigator.geolocation.getCurrentPosition(this.props.GetMyPosition,this.props.GeoError , this.GeoOptions);
}

  render() {
    return (
      <div className="baggrund-baggrund-2">
          <div className="baggrund-0">
              <div className="baggrund-rectangle_2" style={{"background": this.props.color}}>
                  <div className="baggrund-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1a68/882f/28e8dcb780f21fc9bf64142172e72723" className="baggrund-image-7" /> 
                  </div>
                  <div className="baggrund-0-0-1">
                  <button 
                onClick= {this.GetPosition}> {this.props.MyButton} 
                <div className="baggrund-pull_button-9" /> 
                </button> 

                      {/* <div onClick={this.props.MyButton} className="baggrund-pull_button-9" />  */}
                  </div>
                  <div className="baggrund-0-0-2">
                      
                      <p>
                      <div className="baggrund-type_something-4">
                          { this.props.text }
                      </div> </p>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
export default Baggrund;