// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './beskrivelse.css';


export default class Beskrivelse extends React.Component {
  render() {
    return (
      <div className="beskrivelse-beskrivelse-6" /> 
    );
  }
};
