// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './component_1.css';


export default class Component_1 extends React.Component {
  render() {
    return (
      <div className="component_1-component_1">
          <div className="component_1-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1a68/882f/28e8dcb780f21fc9bf64142172e72723" className="component_1-image-7" /> 
          </div>
          <div className="component_1-1">
              <div className="component_1-pull_button-9" /> 
          </div>
      </div>
    );
  }
};
