// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './kort.css';


export default class Kort extends React.Component {
  render() {
    return (
      <div className="kort-kort-000">
          <div className="kort-0">
              <div className="kort-push-0">
                  <div className="kort-0-0-0">
                      <div className="kort-sort_fadende_baggrund-0">
                          <div className="kort-0-0-0-0-0">
                              <div className="kort-udforsk-0000">
                                  <div className="kort-0-0-0-0-0-0-0">
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1a68/882f/28e8dcb780f21fc9bf64142172e72723" className="kort-image-6" /> 
                                  </div>
                                  <div className="kort-0-0-0-0-0-0-1">
                                      <div className="kort-du_er_p_-0">{"DU ER PÅ..."}</div>
                                  </div>
                                  <div className="kort-0-0-0-0-0-0-2">
                                      <div className="kort-line_4" /> 
                                  </div>
                                  <div className="kort-0-0-0-0-0-0-3">
                                      <div className="kort-n_rrebro-0">{"NØRREBRO"}</div>
                                  </div>
                                  <div className="kort-0-0-0-0-0-0-4">
                                      <div className="kort-koncerter_i_n_rheden-0">
                                          {"KONCERTER I NÆRHEDEN"}
                                      </div>
                                  </div>
                                  <div className="kort-0-0-0-0-0-0-5">
                                      <div className="kort-vector-0" /> 
                                  </div>
                                  <div className="kort-0-0-0-0-0-0-6">
                                      <div className="kort-rectangle-00">
                                          <div className="kort-0-0-0-0-0-0-6-0-0">
                                              <div className="kort-rectangle-0">
                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-0">
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-0">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-0-0">
                                                              <div className="kort-image-65">
                                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-0-0-0-0-0">
                                                                      <div className="kort-image-5">
                                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-0-0-0-0-0-0">
                                                                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/970b/f39d/0cde269f06236ead647634846f1ee9bb" className="kort-image-3" /> 
                                                                          </div>
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-0">
                                                              <div className="kort-ellipse-0" /> 
                                                              <div className="kort-ellipse-000">
                                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-0-1-0">
                                                                      <div className="kort-ellipse-00" /> 
                                                                  </div>
                                                              </div>
                                                          </div>
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-1">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-1-0">
                                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-1-0-0">
                                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-1-0-0-0">
                                                                          <div className="kort-line_2" /> 
                                                                          <div className="kort-line_2_" /> 
                                                                          <div className="kort-line_2_1" /> 
                                                                          <div className="kort-ellipse-0000" /> 
                                                                          <div className="kort-ellipse-000000">
                                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-1-0-0-0-4-0">
                                                                                  <div className="kort-ellipse-00000" /> 
                                                                              </div>
                                                                          </div>
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-2">
                                                              <div className="kort-ellipse-000002" /> 
                                                              <div className="kort-ellipse-000003">
                                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-0-1-2-1-0">
                                                                      <div className="kort-ellipse-0000025" /> 
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-2">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-2-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-0-2-0-0">
                                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/5370/caf3/9523a344d4d56815e1d91d674209ca6e" className="kort-image-4" /> 
                                                                  <div className="kort-image-29">
                                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-2-0-0-1-0">
                                                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/5370/caf3/9523a344d4d56815e1d91d674209ca6e" className="kort-image-2" /> 
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-3">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-3-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-0-3-0-0">
                                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/6c65/0b90/8d5766f1ec860f099e033edfa87eb928" className="kort-image-43" /> 
                                                                  <div className="kort-vector-000">
                                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-3-0-0-1-0">
                                                                          <div className="kort-vector-00" /> 
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-0-4">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-4-0">
                                                              <div className="kort-image-8">
                                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-0-4-0-0-0">
                                                                      <div className="kort-image-7">
                                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-0-4-0-0-0-0-0">
                                                                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/876f/061c/62f29ad84c65c7b0816cc28652830787" className="kort-image-1" /> 
                                                                          </div>
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                                  <div className="kort-0-0-0-0-0-0-6-0-0-0-1">
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-1-0">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-1-0-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-1-0-0-0">
                                                                  <div className="kort-udforsk-0">Udforsk</div>
                                                                  <div className="kort-udforsk-00">Udforsk</div>
                                                                  <div className="kort-udforsk-000">Udforsk</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-1-1">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-1-1-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-1-1-0-0">
                                                                  <div className="kort-pr_ferencer-0">{"Præferencer"}</div>
                                                                  <div className="kort-pr_ferencer-00">{"Præferencer"}</div>
                                                                  <div className="kort-pr_ferencer-000">{"Præferencer"}</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-1-2">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-1-2-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-1-2-0-0">
                                                                  <div className="kort-s_g-0">{"Søg"}</div>
                                                                  <div className="kort-s_g-00">{"Søg"}</div>
                                                                  <div className="kort-s_g-000">{"Søg"}</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-1-3">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-1-3-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-1-3-0-0">
                                                                  <div className="kort-kort-0">Kort</div>
                                                                  <div className="kort-minder-0">Minder</div>
                                                                  <div className="kort-kort-00">Kort</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="kort-0-0-0-0-0-0-6-0-0-0-1-4">
                                                          <div className="kort-0-0-0-0-0-0-6-0-0-0-1-4-0">
                                                              <div className="kort-0-0-0-0-0-0-6-0-0-0-1-4-0-0">
                                                                  <div className="kort-indstillinger-0">Indstillinger</div>
                                                                  <div className="kort-indstillinger-00">Indstillinger</div>
                                                                  <div className="kort-indstillinger-000">Indstillinger</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
