// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './kunstner.css';


export default class Kunstner extends React.Component {
  render() {
    return (
      <div className="kunstner-kunstner-0" /> 
    );
  }
};
