// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './pull.css';


export default class Pull extends React.Component {
  render() {
    return (
      <div className="pull-pull-0">
          <div className="pull-0">
              <div className="pull-udforsk-0" /> 
          </div>
      </div>
    );
  }
};
