// Generated by https://pagedraw.io/pages/15246
import  React, { Component } from 'react';
import './pull_knap.css';

class Pull_knap extends React.Component {
  constructor(props) {
    super(props);
    this.state = {  };
    this.GeoOptions = { enableHighAccuracy: true, timeout: 20000, maximumAge: 0, distanceFilter: 1} // Hardcoded for now

    this.GetPosition = this.GetPosition.bind(this);
    
  }

GetPosition()
{

    navigator.geolocation.getCurrentPosition(this.props.GetMyPosition,this.props.GeoError , this.GeoOptions);
}

render() {
  return (
  <div>
    <button  

    onClick = {this.GetPosition}> {this.props.MyButton } 
      <div className="pull_knap-pull_knap-4" /> 
        <div className="pull_knap-0"></div> 
          <div className="pull_knap-0"></div> 
    
    </button>
  </div> );
  
}
}

export default Pull_knap