// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './stedets_navn.css';


export default class Stedets_navn extends React.Component {
  render() {
    return (
      <div className="stedets_navn-stedets_navn-4" /> 
    );
  }
};
