// Generated by https://pagedraw.io/pages/15246
import React from 'react';
import './tekst_med_lokationer.css';


export default class Tekst_med_lokationer extends React.Component {
  render() {
    return (
      <div className="tekst_med_lokationer-tekst_med_lokationer-6" /> 
    );
  }
};
